// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBL3.Data;

#nullable disable

namespace PBL3.Migrations
{
    [DbContext(typeof(MilkTeaDBContext))]
    partial class MilkTeaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PBL3.Models.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("USERS", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PBL3.Models.Customer", b =>
                {
                    b.HasBaseType("PBL3.Models.User");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.ToTable("CUSTOMER", (string)null);
                });

            modelBuilder.Entity("PBL3.Models.Staff", b =>
                {
                    b.HasBaseType("PBL3.Models.User");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WorkShift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("STAFF", (string)null);
                });

            modelBuilder.Entity("PBL3.Models.Customer", b =>
                {
                    b.HasOne("PBL3.Models.User", null)
                        .WithOne()
                        .HasForeignKey("PBL3.Models.Customer", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PBL3.Models.Staff", b =>
                {
                    b.HasOne("PBL3.Models.User", null)
                        .WithOne()
                        .HasForeignKey("PBL3.Models.Staff", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
